/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,js,jsx}",
    "./public/index.html",
    "node_modules/preline/dist/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ["Axiforma", "Calibre", "sans-serif"],
        body: ["Calibre", "sans-serif"],
        monospace: ["Alma Mono", "Courier", "monospace"],
      },
      colors: {
        "primary-lightest": "#e6e6fc",
        "primary-light": "#a8a9fc",
        "primary-base": "#4a4af4",
        "primary-dark": "#2f2fc1",
        "primary-darkest": "#212189",
        "warning-lightest": "#fcf9e8",
        "warning-light": "#ffe98f",
        "warning-base": "#ffca61",
        "warning-dark": "#e88c31",
        "warning-darkest": "#db6414",
        "disabled-background": "#e7e9ea",
        "destructive-lightest": "#f7e3e2",
        "destructive-light": "#feaa97",
        "destructive-base": "#ff6d50",
        "destructive-dark": "#d34333",
        "destructive-darkest": "#93342f",
        "success-lightest": "#e8f9ef",
        "success-light": "#97e8b8",
        "success-base": "#2abc7a",
        "success-dark": "#0a894c",
        "success-darkest": "#105432",
        "gradient-right-dandelion": "linear-gradient(90deg,#ffd072,#ffa900)",
        "gradient-right-indigo": "linear-gradient(90deg,#212189,#000)",
        "max-content-width": "1224",
        "ui-colors-background": "#fff",
        "ui-colors-background-inverse": "#383d49",
        "ui-colors-background-neutral-1": "#f4f3f2",
        "ui-colors-background-neutral-2": "#f0f5f7",
        "ui-colors-border-neutral-1": "#ede9e6",
        "ui-colors-border-neutral-2": "#d3e3ea",
        "ui-colors-text-100": "#101820",
        "ui-colors-text-80": "#3a3c3d",
        "ui-text-dark": "#000",
        "ui-text-light": "#fff",
        "ui-colors-caption": "#6d6e71",
        "ui-grey-a11y": "#6b7280",
        "greyscale-grey-20": "#d4d6d7",
        "greyscale-grey-50": "#909293",
        "greyscale-black-5": "#f7f9fa",
        "greyscale-black-10": "#eef0f1",
        "greyscale-black-20": "#d4d6d7",
        "greyscale-black-30": "#bbbdbe",
        "greyscale-black-40": "#a4a6a7",
        "greyscale-black-50": "#909293",
        "greyscale-black-60": "#747677",
        "greyscale-black-80": "#3a3c3d",
        "greyscale-black-90": "#202223",
        "greyscale-black-100": "#101820",
      },
      screens: {
        // default breakpoints
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        // Height-based breakpoints
        "h-sm": { raw: "(min-height: 640px)" },
        "h-md": { raw: "(min-height: 768px)" },
        "h-lg": { raw: "(min-height: 1024px)" },
        "h-xl": { raw: "(min-height: 1280px)" },
      },
    },
  },
  plugins: [require("preline/plugin")],
};
